package commands

import (
	"fmt"
	"os"
	"path/filepath"
	"text/template"

	"ime-tool/utils"
)

func HandleCreate(cfg Config) error {
	fmt.Println("🚀 Creating new IME project...")
	
	if err := createIME(cfg); err != nil {
		return fmt.Errorf("failed to create IME: %v", err)
	}
	
	return nil
}

func createIME(cfg Config) error {
	fmt.Printf("📁 Creating project: %s\n", cfg.ProjectName)
	
	dirs := []string{
		cfg.ProjectName,
		filepath.Join(cfg.ProjectName, "src"),
		filepath.Join(cfg.ProjectName, "config"),
		filepath.Join(cfg.ProjectName, "build"),
	}

	for _, dir := range dirs {
		if err := os.MkdirAll(dir, 0755); err != nil {
			return fmt.Errorf("failed to create directory %s: %v", dir, err)
		}
		fmt.Printf("✅ Created directory: %s\n", dir)
	}

	// تولید فایل‌ها از تمپلیت
	templates := []struct {
		templateName string
		outputPath   string
	}{
		{"cmake_main.txt", filepath.Join(cfg.ProjectName, "CMakeLists.txt")},
		{"cmake_src.txt", filepath.Join(cfg.ProjectName, "src", "CMakeLists.txt")},
		{"ime.h", filepath.Join(cfg.ProjectName, "src", cfg.IMEName+".h")},
		{"ime.cpp", filepath.Join(cfg.ProjectName, "src", cfg.IMEName+".cpp")},
		{"addon.conf", filepath.Join(cfg.ProjectName, "src", cfg.IMEName+"-addon.conf.in")},
		{"ime.conf", filepath.Join(cfg.ProjectName, "src", cfg.IMEName+".conf")},
	}

	for _, tmpl := range templates {
		if err := generateFromTemplate(tmpl.templateName, tmpl.outputPath, cfg); err != nil {
			return fmt.Errorf("failed to generate %s: %v", tmpl.templateName, err)
		}
		fmt.Printf("✅ Generated: %s\n", tmpl.outputPath)
	}

	configDest := filepath.Join(cfg.ProjectName, "config", cfg.IMEName+".conf")
	if cfg.ConfigFile != "" {
		if err := utils.CopyFile(cfg.ConfigFile, configDest); err != nil {
			return fmt.Errorf("failed to copy config file: %v", err)
		}
		fmt.Printf("✅ Copied config: %s → %s\n", cfg.ConfigFile, configDest)
	} else {
		if err := createDefaultConfig(cfg, configDest); err != nil {
			return fmt.Errorf("failed to create default config: %v", err)
		}
		fmt.Printf("✅ Created default config: %s\n", configDest)
	}

	fmt.Printf("\n🎉 IME project '%s' created successfully!\n", cfg.ProjectName)
	fmt.Printf("📁 Directory: %s\n", cfg.ProjectName)
	fmt.Printf("\nNext steps:\n")
	fmt.Printf("  cd %s\n", cfg.ProjectName)
	fmt.Printf("  ime-tool install -d .\n")
	
	return nil
}

func generateFromTemplate(templateName, outputPath string, cfg Config) error {
	tmplPath := filepath.Join("templates", templateName)
	
	tmpl, err := template.ParseFiles(tmplPath)
	if err != nil {
		return fmt.Errorf("failed to parse template %s: %v", templateName, err)
	}
	
	file, err := os.Create(outputPath)
	if err != nil {
		return fmt.Errorf("failed to create file %s: %v", outputPath, err)
	}
	defer file.Close()
	
	if err := tmpl.Execute(file, cfg); err != nil {
		return fmt.Errorf("failed to execute template %s: %v", templateName, err)
	}
	
	return nil
}

func createDefaultConfig(cfg Config, destPath string) error {
	defaultConfig := fmt.Sprintf(`# %s Configuration
# Auto-generated by ime-tool

[Settings]
convert_numbers=true
unknown_chars_behavior=keep
add_spaces=true
number_separator=$
case_sensitive=false

[Characters]
a=01100001
b=01100010
c=01100011
d=01100100
e=01100101
f=01100110
g=01100111
h=01101000
i=01101001
j=01101010
k=01101011
l=01101100
m=01101101
n=01101110
o=01101111
p=01110000
q=01110001
r=01110010
s=01110011
t=01110100
u=01110101
v=01110110
w=01110111
x=01111000
y=01111001
z=01111010

[Capitals]
A=01000001
B=01000010
C=01000011
D=01000100
E=01000101
F=01000110
G=01000111
H=01001000
I=01001001
J=01001010
K=01001011
L=01001100
M=01001101
N=01001110
O=01001111
P=01010000
Q=01010001
R=01010010
S=01010011
T=01010100
U=01010101
V=01010110
W=01010111
X=01011000
Y=01011001
Z=01011010

[Digits]
0=00110000
1=00110001
2=00110010
3=00110011
4=00110100
5=00110101
6=00110110
7=00110111
8=00111000
9=00111001

[Keywords]
if=0110100101100110
else=01100101011011000111001101100101
for=011001100110111101110010
while=0111011101101000011010010110110001100101

[Operators]
== = 0011110100111101
!= = 0010000100111101
= = 00111101
+ = 00101011
- = 00101101
* = 00101010
/ = 00101111
`, cfg.IMEName)
	
	return os.WriteFile(destPath, []byte(defaultConfig), 0644)
}